### ISSUE TITLE
Translation: it

### ISSUE THREAD

**Issue by Fabio286** [pytesNET/tail.DateTime#10]
### Months
-   January: "Gennaio"
-   February: "Febbraio"
-   March: "Marzo"
-   April: "Aprile"
-   May: "Maggio"
-   June: "Giugno"
-   July: "Luglio"
-   August: "Agosto"
-   September: "Settembre"
-   October: "Ottobre"
-   November: "Novembre"
-   December: "Dicembre"

### Weeks
-   Sunday (SUN): "Domenica (DOM)"
-   Monday (MON): "Lunedì (LUN)"
-   Tuesday (TUE): "Martedì (MAR)"
-   Wednesday (WED): "Mercoledì (MER)"
-   Thursday (THU): "Giovedì (GIO)"
-   Friday (FRI): "Venerdì (VEN)"
-   Saturday (SAT): "Sabato (SAB)"

### Time
-   Hours: "Ore"
-   Minutes: "Minuti"
-   Seconds: "Secondi"

### Strings
-   Select a Month: "Seleziona un mese"
-   Select a Year: "Seleziona un anno"
-   Select a Decade: "Seleziona un decennio"
-   Select a Time: "Seleziona un orario"

**Comment by SamBrishes** [comment]
Hellow.

Thanks for your translation, thats really awesome!

Cordiali saluti,
Sam Brishes da Austria.

**Comment by SamBrishes** [comment]
Hellow,

has been added in 0.4.3

Sincerely,
Sam.
