### ISSUE TITLE
Translation: pt-BR

### ISSUE THREAD

**Issue by juniorgarcia** [pytesNET/tail.DateTime#13]
### Months
-   January: "Janeiro"
-   February: "Fevereiro"
-   March: "Março"
-   April: "Abril"
-   May: "Maio"
-   June: "Junho"
-   July: "Julho"
-   August: "Agosto"
-   September: "Setembro"
-   October: "Outubro"
-   November: "Novembro"
-   December: "Dezembro"

### Weeks
-   Sunday (SUN): "Domingo (Dom)"
-   Monday (MON): "Segunda (Seg)"
-   Tuesday (TUE): "Terça (Ter)"
-   Wednesday (WED): "Quarta (Qua)"
-   Thursday (THU): "Quinta (Qui)"
-   Friday (FRI): "Sexta (Sex)"
-   Saturday (SAT): "Sábado (Sáb)"

### Time
-   Hours: "Horas"
-   Minutes: "Minutos"
-   Seconds: "Segundos"

### Strings
-   Select a Month: "Escolha um mês"
-   Select a Year: "Escolha um ano"
-   Select a Decade: "Escolha uma década"
-   Select a Time: "Escolha um horário"

**Comment by SamBrishes** [comment]
Hellow.

Thanks for your translation and help, that's really awesome!

Sincerely,
Sam!

**Comment by SamBrishes** [comment]
Hellow,

has been added in 0.4.3

Sincerely,
Sam.
