### ISSUE TITLE
incorrect date interpretation?

### ISSUE THREAD

**Issue by mickeybyte** [pytesNET/tail.DateTime#14]
Hi, I just started using the datetime picker to save, retrieve and update a datetime field on MySQL database. 
Saving and updating works just fine, but retrieving the date and showing it in an editable form goes wrong.

I write the following HTML code (from a PHP script): (loaded the necessary JS files of course)
`<input id="datepicker" type="text" name="performance_time" size="20" class="shadeform tail-datetime-field" value="02/01/2019 11:00">`
So this means the date = january 2nd 2019.

At the end of the page, the DateTime picker is added:
`<script type="text/javascript">
            document.addEventListener("DOMContentLoaded", function(){
                tail.DateTime(".tail-datetime-field", { dateFormat:"dd/mm/YYYY", timeFormat:"HH:ii",timeStepMinutes:15,locale:"nl",viewDecades:false,position:"right" });
            });
        </script>`

After the page is loaded, the `<input>` element is changed to:
`<input id="datepicker" type="text" name="performance_time" size="20" class="shadeform tail-datetime-field" value="02/01/2019 11:00" data-tail-datetime="tail-1" data-value="1549015200000">`

However it shows in the textbox as **01/02**/2019 11:00 in stead of **02/0**1/2019 11:00 as set in the "VALUE"
Also in the datepicker it is shown as february 1st 2019. 

So it seems its switching day and month.

When I try the same thing with date January 30th, 2019 it interprets day and month correctly. 

Is this a bug in the script, or do I need to change some options or code?

Thanks,
Michiel.

**Comment by mickeybyte** [comment]
Sam,

Thanks for the quick response. I'll have a look at it tomorrow.

Whish you a Happy Christmas!

Michiel.

**Comment by SamBrishes** [comment]
No problem, 

I wish you also a Merry Christmas. :3
