### ISSUE TITLE
REQ: up/down minutes & close buttons

### ISSUE THREAD

**Issue by mickeybyte** [pytesNET/tail.DateTime#15]
2 small requests for a future version :-)

1) When clicking the up/down buttons make it an endless loop, so don't stop at 23h but go to 0h, after 59min goto 0 minutes. (I noticed this because I had set the min interval on 15 and I choose 20h and then clicked the up button to go from 45min to 0, but that didn't work, I had to click down to 0)
2) Add a small button to close the datetime picker (maybe optional with parameter). I've tried to "tab" out of the field, but the datetime picker doesn't hide then. I had to click away from the date field)

I can send you the dutch translation file. It's not much, but it's the least I can give in return!

Thanks,
Michiel.

**Comment by mickeybyte** [comment]
`/*
 |  tail.datetime - A vanilla JavaScript DateTime Picker without dependencies!
 |  @file       ./langs/tail.datetime-de.js
 |  @author     SamBrishes <sam@pytes.net>
 |  @version    0.4.3 - Beta
 |
 |  @website    https://github.com/pytesNET/tail.DateTime
 |  @license    X11 / MIT License
 |  @copyright  Copyright © 2018 SamBrishes, pytesNET <info@pytes.net>
 */
;(function(factory){
   if(typeof(define) == "function" && define.amd){
       define(function(){
           return function(datetime){ factory(datetime); };
       });
   } else {
       if(typeof(window.tail) != "undefined" && window.tail.DateTime){
           factory(window.tail.DateTime);
       }
   }
}(function(datetime){
    datetime.strings.register("nl", {
        months: ["januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december"],
        days:   ["zondag", "maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag"],
        shorts: ["ZO", "MA", "DI", "WO", "DO", "VR", "ZA"],
        time:   ["uur", "minuten", "seconden"],
        header: ["kies een maand", "kies een jaar", "kies een decennium", "kies een tijdstip"]
    });
    return datetime;
}));
`

**Comment by SamBrishes** [comment]
Hellow,

thanks for your translation! I've added it + both of your requested features. The close button can be enabled and disabled using the `closeButton` option (the close button will be hidden, if the DateTime field is static and set to "stay open").

There is also a new option called `timeIncrement`, which increase the next unit after looping the previous one. So if you go from "55 Seconds" to "0 Seconds" (Using the Up Button) the Minutes will increase from 12 (for example) to 13 too.

Happy new Year. :tada: 

Sincerely,
Sam.
