### ISSUE TITLE
When showing only time picker, the calendar label says undefined

### ISSUE THREAD

**Issue by thollenberg** [pytesNET/tail.DateTime#16]
I have a time picker defined which works perfectly apart from the label which says 'undefined'.
`tail.DateTime(".hasTimepicker", {
	locale: "en",
	timeFormat: "HH:ii",
	dateFormat: false
});
`
generates

![image](https://user-images.githubusercontent.com/5890658/50632856-7fa41600-0f49-11e9-9ee5-0e0f703fb368.png)

**Comment by SamBrishes** [comment]
Hellow,

Thanks for sharing this bug. I will try to fix it as fast as possible. 

Sincerely, 
Sam.

**Comment by SamBrishes** [comment]
Hellow,

your Issue is fixed in version 0.4.6.

Sincerely,
Sam.
