### ISSUE TITLE
Tooltips are behind colored tiks.

### ISSUE THREAD

**Issue by FlashPanther** [pytesNET/tail.DateTime#21]
Tooltips are behind colored tiks.

![Imgur Image](https://i.imgur.com/rfkCOPq.png)

**Comment by SamBrishes** [comment]
Hellow,

thanks, and as your fixs shows a `z-index` property will solve this issue immedatly. But I prefer to set this within the CSS file(s), to keep the JavaScript as free as possible from "custom stylings".

Sincerely,
Sam.

**Comment by FlashPanther** [comment]
> Hellow,
> 
> thanks, and as your fixs shows a `z-index` property will solve this issue immedatly. But I prefer to set this within the CSS file(s), to keep the JavaScript as free as possible from "custom stylings".
> 
> Sincerely,
> Sam.

Absolutely true! 

Are you using a bundler or tool (such as webpack for example) to generate css files ?

**Comment by SamBrishes** [comment]
Hellow,

Nope, I'm just using Less as Pre-Processor and a small node.js-based compiler script ([depending on the project](https://github.com/pytesNET/wp-theme/blob/master/less/build.js)). I'm not really into these bundler and utility stuff. 

Sincerely,
Sam.
