### ISSUE TITLE
Time Picker

### ISSUE THREAD

**Issue by Charles-Goodwin** [pytesNET/tail.DateTime#23]
I chose your date/time picker as it looked the best but there is always room for improvement
The 24 hour clock is normally illustrated like so 01:00:00
But the input fields currently don't have leading zeros for hours minutes and seconds

Also I see you have added the feature to disable the seconds.
Could you go one step further and allow the config to remove the seconds.

Thanks
Charlie

**Comment by SamBrishes** [comment]
Hellow,

thanks for your request. 

I'm using the "number" input type, which removes leading zeros per default. But there should be a (inofficial) solution, which keeps them. This solution works only in modern browsers, but I guess it's the best way. I'll try and implement it.

I guess, that should be possible too. I'll try to find a good solution for this.

Thanks.

Sincerely,
Sam.

**Comment by MatthewRLarsen** [comment]
I also love the interface for the date/time picker. Nice job!

FYI, I would also like to remove the seconds altogether and show AM/PM selector instead. As we are using am/pm (12 hour) for time display, is there a setting for showing the selection of AM vs PM? I am not certain if I am missing it, or it is not yet an option.

Best regards,
Matt.

**Comment by SamBrishes** [comment]
Hellow,

thanks :D and no, the current version doesn't offer such an option. I'll add an AM/PM in the next release.

Sincerely,
Sam

**Comment by hmzlam** [comment]
to remove second try this after timepicker init code
```
  $(".timepicker-seconds").css("display","none");
  $(".timepicker-field").css("width","40%");
  $(".timepicker-field:first-child").css("width","45%");

```

**Comment by SamBrishes** [comment]
Hellow,

sorry for the long wait! 

I'm currently working on version 0.4.13, which contains some bugfixes and design-changes as well as a completely re-newed TimePicker interface. The new interface contains a custom AM/PM switch (need to be activated manually, through the new `time12h` option), custom step buttons on the number fields and each single of the 3 fields can be just "disabled" and also hidden / removed completely.

![new calendar](https://user-images.githubusercontent.com/31392477/59192325-5899e200-8b82-11e9-9199-89a491a367b5.gif)

(PS.: The shown design above isn't "final", it may gets changed during dev.)

Thanks,

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

sorry for the long wait. The new update is out now and implements:

- Leading Zeros on the single time fields (not as shown on the GIF above)
- an AM/PM selector to use 12-hours clock
- the possibility to "remove" hours/minutes/seconds by passing `false` on the respective `time*` option.

Thanks for your contribution and suggestions!

Sincerely,
Sam.
