### ISSUE TITLE
should close (or test with stayopen) after submit time

### ISSUE THREAD

**Issue by hmzlam** [pytesNET/tail.DateTime#24]
https://github.com/pytesNET/tail.DateTime/blob/a665fd8c0948204b7773b536e5ed80807ea0a441/js/tail.datetime.js#L369

this should be at least
`
case "submit":

this.close();

 return this.selectDate(this.fetchDate(parseInt(elem[a]("data-date"))));
`

**Comment by SamBrishes** [comment]
Hello,

sorry for the long wait and thanks for your request. I added your [suggestion](https://github.com/pytesNET/tail.DateTime/blob/master/js/tail.datetime.js#L393).

Thanks.

Sincerely,
Sam.
