### ISSUE TITLE
Can't resolve '../tail.datetime-default.css'

### ISSUE THREAD

**Issue by evperedadiaz** [pytesNET/tail.DateTime#25]
Hi,
When I import `tail.datetime/css/tail.datetime-default-orange.css` into my style.css, it shows me this error:
`Module not found: Error: Can't resolve '../tail.datetime-default.css' in '/xxx/node_modules/tail.datetime/css'.`

I thinks It's because `tail.datetime-default-orange.css` import `tail.datetime-default.css` as if it were outside the directory.

**Comment by SamBrishes** [comment]
Hellow,

I'm really sorry for that! This error should be solved by changing the directory pathing of the [@import rule](https://github.com/pytesNET/tail.DateTime/blob/master/css/tail.datetime-default-orange.css#L12) into the following one (so just remove the `../`, to "jump" into the parent directory):

```css
@import url("tail.datetime-default.css");
```

Thanks for reporting this issue!

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

this issue has been fixed with Version 0.4.9. Thanks.

Sincerely,
Sam.
