### ISSUE TITLE
Error in last line of both css/tail.datetime-default-blue.css  -green.css - transposed

### ISSUE THREAD

**Issue by jimruss1** [pytesNET/tail.DateTime#27]

**Comment by SamBrishes** [comment]
Hellow,

thanks for reporting, but I don't see any error? What do you mean exactly? 

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

I guess this issue is clear? 

I close it for now, if you still have any question, feel free to reopen it.

Thanks.

Sincerely, 
Sam.
