### ISSUE TITLE
No language program for English(American)

### ISSUE THREAD

**Issue by jimruss1** [pytesNET/tail.DateTime#29]
For the download ver 0.4.7, I find 11 language files 
None are for English or American language
I did note that version 0.4.8 contained a new file for French
What am I missing?

**Comment by SamBrishes** [comment]
Hellow,

the english language strings are included [in the main file itself](https://github.com/pytesNET/tail.DateTime/blob/master/js/tail.datetime.js#L167).

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

I guess this issue is clear? 

I close it for now, if you still have any question, feel free to reopen it.

Thanks.

Sincerely, 
Sam.
