### ISSUE TITLE
Date picker is not positioned properly in a child scrollable container

### ISSUE THREAD

**Issue by jfdesrochers** [pytesNET/tail.DateTime#33]
When used inside a container with overflow: auto set, the calendar doesn't follow scrolling like it would do if the body was scrolling. See: https://jsfiddle.net/5hrbpsav/1/ for example.

Looking at the code, the calculations in calcPosition don't seem to account for the current scroll position. When the only scrolling element is the body, this poses no issue since the 'absolute' position of the input element will stay the same. However when a child element is made scrollable, the input's position in relation with the viewport will change as we scroll thus the 'offsetTop' alone will no longer reflect the current position and the datepicker will open at a wrong place.

**Comment by jfdesrochers** [comment]
One potential solution could be to use the method "getBoundingClientRect" instead of "offsetTop". Example: https://jsfiddle.net/dmLu3j20/

**Comment by SamBrishes** [comment]
Hellow,

Thanks for your issue / bug report and the direct solution on Top! :D I'll add this fix on version 0.4.13, which should be released very soon.

Thanks.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

sorry for the long wait, the issue has been fixed in Version 0.4.13.

Thanks for your contribution!

Sincerely,
Sam.
