### ISSUE TITLE
Translation: es_MX

### ISSUE THREAD

**Issue by elPesecillo** [pytesNET/tail.DateTime#34]
`### Months`
`-   January: "Enero"`
`-   February: "Febrero"`
`-   March: "Marzo"`
`-   April: "Abril"`
`-   May: "Mayo"`
`-   June: "Junio"`
`-   July: "Julio"`
`-   August: "Agosto"`
`-   September: "Septiembre"`
`-   October: "Octubre"`
`-   November: "Noviembre"`
`-   December: "Diciembre"`

`### Weeks`
`-   Sunday (SUN): "Domingo (do)"`
`-   Monday (MON): "Lunes (lu)"`
`-   Tuesday (TUE): "Martes (ma)"`
`-   Wednesday (WED): "Miercoles (mi)"`
`-   Thursday (THU): "Jueves (ju)"`
`-   Friday (FRI): "Viernes (vi)"`
`-   Saturday (SAT): "Sábado (sá)"`

`### Time`
`-   Hours: "Horas"`
`-   Minutes: "Minutos"`
`-   Seconds: "Segundos"`

`### Strings`
`-   Select a Month: "Selecciona un Mes"`
`-   Select a Year: "Selecciona un Año"`
`-   Select a Decade: "Selecciona una Decada"`
`-   Select a Time: "Selecciona la hora"`

**Comment by SamBrishes** [comment]
Hellow,

Thanks for your translation, I'll add it to the next release (0.4.13) really soon.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

thanks for waiting and your translation, of course. Version 0.4.13 is out now and implements the new language!

Sincerely,
Sam
