### ISSUE TITLE
Not working in Bootstrap modal window

### ISSUE THREAD

**Issue by aeadedoyin** [pytesNET/tail.DateTime#37]
The picker is not working/showing in Bootstrap Modals

**Comment by SamBrishes** [comment]
Hellow,

thanks for mention this issue and for the fix too, of course. The next version will handle the respective properties directly in the stylesheet (I want to use as less CSS as possible in the JavaScript source).

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

sorry for the long wait, the issue has been fixed in Version 0.4.13.

Thanks for your contribution!

Sincerely,
Sam.
