### ISSUE TITLE
Dates before 1970-01-01 are disabled.

### ISSUE THREAD

**Issue by tsakal** [pytesNET/tail.DateTime#40]
To solve this,
change the line: this.con.dateStart = parse(this.con.dateStart, true, true) || 0;
whith this one: this.con.dateStart = parse(this.con.dateStart, true, true) || -9999999999999;

**Comment by SamBrishes** [comment]
Hellow,

thanks for reporting this issue and adding a fix too. :D 

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

sorry for the long wait, the issue has been fixed in Version 0.4.13.

Thanks for your contribution!

Sincerely,
Sam.
