### ISSUE TITLE
Translation: {el}

### ISSUE THREAD

**Issue by tsakal** [pytesNET/tail.DateTime#41]
### Months
-   January: "Ιανουάριος"
-   February: "Φεβρουάριος"
-   March: "Μάρτιος"
-   April: "Απρίλιος"
-   May: "Μάιος"
-   June: "Ιούνιος"
-   July: "Ιούλιος"
-   August: "Αύγουστος"
-   September: "Σεπτέμβριος"
-   October: "Οκτώβριος"
-   November: "Νοέμβριος"
-   December: "Δεκέμβριος"

### Weeks
-   Sunday (SUN): "Κυριακή (ΚΥΡ)"
-   Monday (MON): "Δευτέρα (ΔΕΥ)"
-   Tuesday (TUE): "Τρίτη (ΤΡΙ)"
-   Wednesday (WED): "Τετάρτη (ΤΕΤ)"
-   Thursday (THU): "Πέμπτη (ΠΕΜ)"
-   Friday (FRI): "Παρασκευή (ΠΑΡ)"
-   Saturday (SAT): "Σάββατο (ΣΑΒ)"

### Time
-   Hours: "Ώρες"
-   Minutes: "Λεπτά"
-   Seconds: "Δευτερόλεπτα"

### Strings
-   Select a Month: "Επιλογή Μηνός"
-   Select a Year: "Επιλογή Έτους"
-   Select a Decade: "Επιλογή Δεκαετίας"
-   Select a Time: "Επιλογή Ώρας"

**Comment by SamBrishes** [comment]
Hellow,

thanks for your translation, that's really awesome! 

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

thanks for waiting and your translation, of course. Version 0.4.13 is out now and implements the new language!

Sincerely,
Sam
