### ISSUE TITLE
Calculations are wrong in some environments

### ISSUE THREAD

**Issue by dimadin** [pytesNET/tail.DateTime#6]
Although I don't know if this is error with library, in some cases popup calendar is positioned too left so part of left side is not visible, and in the same time time selector is broken in two rows with seconds selector being in second row. 

Check these two examples: difference is that in second case Bootstrap is used.
https://codepen.io/kiroprac/full/XyyBKL
https://codepen.io/kiroprac/full/xQQyEy

Note that I have this same problem in existing application when using this library so it's not because HTML/CSS is empty (as in first example), I can create demo if you want to check it too.

**Comment by ashucg** [comment]
@dimadin you can fix time selector issue by adding following to your application:
```
.tail-datetime-calendar,
.tail-datetime-calendar * {
    box-sizing: border-box;
}
.tail-datetime-calendar .calendar-timepicker .timepicker-field input[type="number"] {
    line-height: 1.6;
}
```

**Comment by SamBrishes** [comment]
Hellow,

Im sorry for the long wait, Im currently really busy. The current master branch contains an improved JS-side position calculation, to prevent the datetime calendar to go "offscreen" AND @ashucg's bugfix for the input fields (Thanks!).

Thanks for reporting, the Release (0.4.2) will be published during the next week (please use the master branch until then).

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

Version 0.4.2 has been released just now and contains a Fix for this issue.

Sincerely,
Sam.
