### ISSUE TITLE
Dont close when input lose focus

### ISSUE THREAD

**Issue by vjmartins** [pytesNET/tail.DateTime#60]
Hi.

I have two inputs with tail.DateTime. When i write date in first input and press key TAB, the DateTime in the first dont close.

Sorry my english. ;)

**Comment by SamBrishes** [comment]
Hellow,

thanks for your issue. Seems like a bug, I'll try to fix it until the new version gets released you can use a small workaround [as shown on this CodePen](https://codepen.io/sambrishes/pen/GVyyjq):

```javascript
let unique = tail.DateTime("input#date-one");

unique.e.addEventListener("blur", function(event){
	unqiue.close();
});
```

No Problem :D 

Sincerely,
Sam.
