### ISSUE TITLE
Error with Time picker

### ISSUE THREAD

**Issue by nicoonline** [pytesNET/tail.DateTime#87]
Hello,

We have an alert on the time picker when we select the hour.

![image](https://user-images.githubusercontent.com/2115195/67787568-17429a00-fa71-11e9-9f55-09e0caa4818f.png)

=> Please modify the value to match the expected format.

**Comment by nicoonline** [comment]
code used:

<link rel="stylesheet" href="modules/DateTime/css/tail.datetime-default-red.css">
<script src="modules/DateTime/js/tail.datetime.min.js"></script>


<input type="hidden" name="requestdate" id="demo" class="demo">
<div id="datetime-demo-holder" class="datetime-folder"></div>

<script>          

tail.DateTime("#demo", {
    position: "#datetime-demo-holder",
    dateFormat: "YYYY-mm-dd", 
    timeFormat: "HH:ii:ss",
    weekStart: 1,
    zeroSeconds: false,
    dateBlacklist: false,
    timeHours: 0,
    timeMinutes: 0,
    timeSeconds:null,    
   startOpen: true,
    timeIncrement: true,
    stayOpen: true,
    timeStepHours: 1,
    timeStepMinutes: 30,
    timeStepSeconds: 60,
    dateRanges: [
    {
        start: new Date(2019,10,02),
        end: new Date(2019,12,08),
        days: ["MON","TUE","WED","THU","FRI"]
                    }
                        ]   
                });  
</script>

**Comment by nicoonline** [comment]
Hello,

I looked on this and found the issue :+1: 

When the time picker is in a form and there was an other form on the same page, it's  failing.

ex:

`<form id=2 name=2 action=test2.html method=post>
kldekldfke
</form>

<form action=test3.html>

<link rel="stylesheet" href="modules/DateTime/css/tail.datetime-default-red.css">
<script src="modules/DateTime/js/tail.datetime.min.js"></script>

<input type="hidden" name="requestdate" id="demo" class="demo">
<div id="datetime-demo-holder" class="datetime-folder"></div>

<script>
tail.DateTime("#demo", {
position: "#datetime-demo-holder",
dateFormat: "YYYY-mm-dd",
timeFormat: "HH:ii:ss",
weekStart: 1,
zeroSeconds: false,

timeHours: 0,
timeMinutes: 0,
timeSeconds:null,
 startOpen: true,
 dateBlacklist: false,
 timeIncrement: true,
 stayOpen: true,
 timeStepHours: 1,
 timeStepMinutes: 30,
 timeStepSeconds: 60,
dateRanges: [
{
start: new Date(2019,10,03),
end: new Date(2019,12,09),
days: ["MON","TUE","WED","THU","FRI"]
}
] 
});

 </script>
</form>

OK `

**Comment by nicoonline** [comment]
Any updates ?

**Comment by nicoonline** [comment]
....

**Comment by jnguiot** [comment]
I believe it is a duplicate of my issue  #101 . I should have read the others before opening mine. Please note you are probably impacted by #103 . PRs have been submitted.

**Comment by nicoonline** [comment]
indeed it's the problem but should be fix in the three .js files and not one of the three :)

**Comment by nicoonline** [comment]
it's not totally fixed jnguiot.
It's fixed on the selector but not when we submit the form ... can you find why ? :)

**Comment by jnguiot** [comment]
> should be fix in the three .js files and not one of the three :)

Which three js file are you talking about?

>  It's fixed on the selector but not when we submit the form ... can you find why ? :)

Actually, using the html you gave, it works on my browser (latest FF). Which browser are you using? Can you check the pattern (right click on the field : inspect. Pattern should be equal to `\d*`)

**Comment by nicoonline** [comment]
[root@ns1 js]# ls -lh
total 176K
-rw-r--r-- 1 root root 62K Apr 15 18:18 tail.datetime-full.js
-rw-r--r-- 1 root root 32K Jul 31  2019 tail.datetime-full.min.js
-rw-r--r-- 1 root root 53K Apr 15 18:20 tail.datetime.js
-rw-r--r-- 1 root root 24K Oct 30 08:57 tail.datetime.min.js

**Comment by jnguiot** [comment]
Hum, that's four. And I applied the fix in all four: https://github.com/jnguiot/tail.DateTime/commit/a1b6866f2b6f507a582323655846d327a5e88813

**Comment by nicoonline** [comment]
I'm also using FF:
![Capture](https://user-images.githubusercontent.com/2115195/79364164-3cf12c00-7f49-11ea-8c92-a142feaebb6f.JPG)

**Comment by nicoonline** [comment]
> 
> 
> Hum, that's four. And I applied the fix in all four: [jnguiot@a1b6866](https://github.com/jnguiot/tail.DateTime/commit/a1b6866f2b6f507a582323655846d327a5e88813)

indeed :)

**Comment by jnguiot** [comment]
Pattern is still broken in your form. Can you check if the file used is the one from my repo? Look for \\d* in the file. Please note that the PR is not merged, thus the master branch of this repo is not fixed.

**Comment by nicoonline** [comment]
> 
> 
> > should be fix in the three .js files and not one of the three :)
> 
> Which three js file are you talking about?
> 
> > It's fixed on the selector but not when we submit the form ... can you find why ? :)
> 
> Actually, using the html you gave, it works on my browser (latest FF). Which browser are you using? Can you check the pattern (right click on the field : inspect. Pattern should be equal to `\d*`)

It's missing the  \ in the pattern.
With \d*, it's working :)

**Comment by nicoonline** [comment]
OK fixed in my version. Thanks a lot jnguiot, great help !
